function (get_environment_mpi_paths arg_mpilib arg_mpiinclude arg_mpilibname)
  if (WIN32)
    if (GLOBALIZER_MPI MATCHES "ms")
      set_path(MPI_INCLUDE $ENV{MSMPI_INC})
      select_platform_depended_library(MPI_LIB "$ENV{MSMPI_LIB32}" "$ENV{MSMPI_LIB64}")
      set(${arg_mpilib} ${MPI_LIB} PARENT_SCOPE)
      set(${arg_mpiinclude} ${MPI_INCLUDE} PARENT_SCOPE)
      set(${arg_mpilibname} "msmpi" PARENT_SCOPE)
    elseif(GLOBALIZER_MPI MATCHES "mpich1")
      set_path(MPI_INCLUDE $ENV{MPICH1_INC})
      select_platform_depended_library(MPI_LIB "$ENV{MPICH1_LIB32}" "$ENV{MPICH1_LIB64}")
      set(${arg_mpilib} ${MPI_LIB} PARENT_SCOPE)
      set(${arg_mpiinclude} ${MPI_INCLUDE} PARENT_SCOPE)
      set(${arg_mpilibname} "mpich" PARENT_SCOPE)
    elseif(GLOBALIZER_MPI MATCHES "mpich2")
      set_path(MPI_INCLUDE $ENV{MPICH2_INC})
      select_platform_depended_library(MPI_LIB "$ENV{MPICH2_LIB32}" "$ENV{MPICH2_LIB64}")
      set(${arg_mpilib} ${MPI_LIB} PARENT_SCOPE)
      set(${arg_mpiinclude} ${MPI_INCLUDE} PARENT_SCOPE)
      set(${arg_mpilibname} "mpi" PARENT_SCOPE)
	elseif(GLOBALIZER_MPI MATCHES "intel")
		find_package(MPI REQUIRED COMPONENTS CXX)

		if(NOT MPI_CXX_FOUND)
			message(FATAL_ERROR "Intel MPI was not found")
		endif()

		if(NOT TARGET MPI::MPI_CXX)
			message(FATAL_ERROR "MPI::MPI_CXX target was not created")
		endif()

		message(STATUS "Intel MPI found")
		message(STATUS "MPI include dirs: ${MPI_CXX_INCLUDE_DIRS}")
		message(STATUS "MPI libraries: ${MPI_CXX_LIBRARIES}")

		set(${arg_mpiinclude} ${MPI_CXX_INCLUDE_DIRS} PARENT_SCOPE)
		set(${arg_mpilib} MPI::MPI_CXX PARENT_SCOPE)
		set(${arg_mpilibname} "" PARENT_SCOPE)
	endif()
  elseif (UNIX)
	find_package(MPI REQUIRED COMPONENTS CXX)

	set(${arg_mpiinclude} ${MPI_CXX_INCLUDE_DIRS} PARENT_SCOPE)
	set(${arg_mpilib} ${MPI_CXX_LIBRARIES} PARENT_SCOPE)
	set(${arg_mpilibname} "" PARENT_SCOPE)
  endif()
endfunction()

macro (init_stub_mpi)
  set(STUB_MPI_INCLUDE ${PROJECT_SOURCE_DIR}/lib/mpi_stub/include)
  set(STUB_MPI_SRC ${PROJECT_SOURCE_DIR}/lib/mpi_stub/src/StubMPI.cpp)
  set(STUB_MPI_LIB mpi_stub)
  add_library(${STUB_MPI_LIB} STATIC ${STUB_MPI_SRC})
  target_include_directories(${STUB_MPI_LIB} PUBLIC ${STUB_MPI_INCLUDE})
endmacro()

function (setup_mpi arg_usempi arg_mpilib arg_mpiinclude)

  if(NOT ${arg_usempi})
    message(STATUS "Stub implementation of the MPI standard is used. Multi-process run modes are unavaliable.")
    init_stub_mpi()
    set(${arg_mpiinclude} ${STUB_MPI_INCLUDE} PARENT_SCOPE)
    set(${arg_mpilib} ${STUB_MPI_LIB} PARENT_SCOPE)
    return()
  endif()

  get_environment_mpi_paths(DEFAULT_MPI_LIB DEFAULT_MPI_INCLUDE DEFAULT_MPI_LIB_NAME)
  
  if(GLOBALIZER_MPI MATCHES "intel")
	set(OUTPUT_MPI_INCLUDE ${DEFAULT_MPI_INCLUDE})
	set(OUTPUT_MPI_LIB ${DEFAULT_MPI_LIB})
  else()
    if (GLOBALIZER_MPI_LIB_USER_PATH STREQUAL "")
	  if (WIN32)
	    set(OUTPUT_MPI_LIB "${DEFAULT_MPI_LIB}/${DEFAULT_MPI_LIB_NAME}")
    
		if(NOT OUTPUT_MPI_LIB MATCHES "\\.lib$")
			string(APPEND OUTPUT_MPI_LIB ".lib")
		endif()
    
	  else()
	    set(OUTPUT_MPI_LIB ${DEFAULT_MPI_LIB})
	  endif(WIN32)
    else()
	  set(OUTPUT_MPI_LIB ${GLOBALIZER_MPI_LIB_USER_PATH})
    endif()
	  if (GLOBALIZER_MPI_INCLUDE_USER_PATH STREQUAL "")
	  set(OUTPUT_MPI_INCLUDE ${DEFAULT_MPI_INCLUDE})
    else()
	  set(OUTPUT_MPI_INCLUDE ${GLOBALIZER_MPI_INCLUDE_USER_PATH})
    endif()
  endif()

  set(${arg_mpiinclude} ${OUTPUT_MPI_INCLUDE} PARENT_SCOPE)
  set(${arg_mpilib} ${OUTPUT_MPI_LIB} PARENT_SCOPE)

  if(${GLOBALIZER_CMAKE_VERBOSE})
    message("MPI include dir: " ${OUTPUT_MPI_INCLUDE})
    message("MPI lib: " ${OUTPUT_MPI_LIB})
  endif()

endfunction (setup_mpi)
